name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Accept SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Build project
      run: ./gradlew build --stacktrace --no-daemon

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest --stacktrace --continue --no-daemon
      if: success() || failure()

    - name: Run Lint
      run: ./gradlew lintDebug --stacktrace --continue --no-daemon
      if: success() || failure()

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/reports/
          app/build/test-results/
