name: Android CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.6'
      - name: Build Debug APK
        run: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:lintDebug
          ./gradlew test
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
